source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

gem 'bootsnap', '>= 1.4.4', require: false
gem 'faraday', '~> 0.15'
gem 'hamlit', '~> 2.14', '>= 2.14.4'
gem 'high_voltage', '~> 3.1'
#gem 'jbuilder', '~> 2.5'
gem 'puma', '~> 3.11'
gem 'rails', '~> 5.2.0'
gem 'sass-rails', '~> 5.0'
gem 'sqlite3'
gem 'turbolinks', '~> 5'
#gem 'uglifier', '>= 1.3.0'
gem 'webpacker', '~> 5.0'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 4.0'
end

group :development do
  gem 'foreman', require: false
  gem 'listen', '~> 3.3'
  gem 'pry-remote'
  gem 'spring'
  gem 'web-console', '< 4'
end
